<?php
/**
 * Shared Site Health mock detection for auto-update filters.
 *
 * Synthetic offers injected by {@see WP_Site_Health::detect_plugin_theme_auto_update_issues()}
 * must bypass delay and safe-mode gates so that the Site Health screen does not report
 * false "auto-updates disabled" warnings.
 *
 * @package updatronix
 * @since 1.1.2
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Check whether an auto-update offer is a Site Health synthetic probe.
 *
 * Covers the well-known mock objects injected by
 * WP_Site_Health when it round-trips wp_is_auto_update_forced_for_item()
 * through the auto_update_{$type} filter chain, plus any plugin/theme
 * offer whose file/stylesheet is not present on disk.
 *
 * Core and translation offers are never generated by Site Health's probe.
 *
 * @since 1.1.2
 *
 * @param string $type Update type: 'plugin', 'theme', 'core', or 'translation'.
 * @param object $item The update item object from the filter.
 * @return bool True when the offer is a synthetic Site Health mock or references a missing file.
 */
function updatronix_is_site_health_mock(string $type, object $item): bool {
    if ($type === 'plugin') {
        $file = isset($item->plugin) ? (string) $item->plugin : '';
        if ($file === '') {
            return false;
        }

        if ($file === 'a-fake-plugin/a-fake-plugin.php') {
            return true;
        }

        return !file_exists(WP_PLUGIN_DIR . '/' . $file);
    }

    if ($type === 'theme') {
        $stylesheet = isset($item->theme) ? (string) $item->theme : '';
        if ($stylesheet === '') {
            return false;
        }

        if ($stylesheet === 'a-fake-theme') {
            return true;
        }

        return !wp_get_theme($stylesheet)->exists();
    }

    return false;
}